version: '3.9'

networks:
    shruti-network-kt:
        external: true

services: 

  mysqlshrutidb:
    image: mysql
    environment:
      - MYSQL_DATABASE=practice
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3308:3306
    networks:
      - shruti-network-kt
    volumes:
      - ./volume-shruti:/var/lib/mysql

  kt-project:
    image: shruti-poc
    restart: on-failure
    depends_on:
      - mysqlshrutidb
    ports:
      - 8082:8080
    environment:
      - MYSQL_HOST=mysqlshrutidb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_PORT=3306
    networks:
      - shruti-network-kt
    volumes:
      - ./volume-shruti:/var/lib/mysql

